"""Comprehensive test suite for OpenPGP release authenticity and SHA-256 integrity verification."""

import hashlib
import json
from pathlib import Path
import tempfile
import unittest
import warnings

import pgpy
from pgpy.constants import CompressionAlgorithm, HashAlgorithm, KeyFlags, PubKeyAlgorithm, SymmetricKeyAlgorithm

from vrka_core.release_verifier import (
    TRUSTED_VRKA_RELEASE_KEY_FINGERPRINT,
    TRUSTED_VRKA_RELEASE_KEY_PEM,
    compute_file_sha256,
    parse_sha256sums,
    verify_openpgp_signature,
    verify_release_artifact,
)


def _generate_ephemeral_keypair(identity: str = "Untrusted Test Key"):
    """Generate an in-memory key pair for test scenarios without persisting private material."""
    key = pgpy.PGPKey.new(PubKeyAlgorithm.RSAEncryptOrSign, 2048)
    uid = pgpy.PGPUID.new(identity, email="test@example.com")
    key.add_uid(
        uid,
        usage={KeyFlags.Sign},
        hashes=[HashAlgorithm.SHA256],
        ciphers=[SymmetricKeyAlgorithm.AES256],
        compression=[CompressionAlgorithm.ZLIB],
    )
    return key


class ReleaseAuthenticityTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        # Generate an ephemeral signing key for test generation
        cls.test_signer_key = _generate_ephemeral_keypair("VRKA Trusted Test Key")
        cls.test_trusted_pub_pem = str(cls.test_signer_key.pubkey)
        cls.test_trusted_fp = str(cls.test_signer_key.pubkey.fingerprint)

        # Generate an untrusted / third-party key
        cls.untrusted_key = _generate_ephemeral_keypair("Attacker Fake Key")
        cls.untrusted_pub_pem = str(cls.untrusted_key.pubkey)
        cls.untrusted_fp = str(cls.untrusted_key.pubkey.fingerprint)

    def setUp(self):
        self.temp_dir = tempfile.TemporaryDirectory()
        self.work_dir = Path(self.temp_dir.name)

    def tearDown(self):
        self.temp_dir.cleanup()

    def test_valid_signature_authenticates(self):
        """Valid OpenPGP signature generated by trusted key must pass."""
        payload = "64f0b2... *VRKA-4.5.0-Build-018-Portable.zip\n"
        sig = str(self.test_signer_key.sign(payload.encode("utf-8")))

        res = verify_openpgp_signature(
            content=payload,
            signature=sig,
            trusted_pubkey_pem=self.test_trusted_pub_pem,
            expected_fingerprint=self.test_trusted_fp,
        )
        self.assertTrue(res.is_valid)
        self.assertEqual(res.fingerprint, self.test_trusted_fp)
        self.assertEqual(res.error, "")

    def test_invalid_signature_fails_closed(self):
        """Corrupted signature payload must be rejected fail-closed."""
        payload = "64f0b2... *VRKA-4.5.0-Build-018-Portable.zip\n"
        sig = str(self.test_signer_key.sign(payload.encode("utf-8")))
        # Corrupt the ASCII armor
        corrupted_sig = sig.replace("A", "B", 5)

        res = verify_openpgp_signature(
            content=payload,
            signature=corrupted_sig,
            trusted_pubkey_pem=self.test_trusted_pub_pem,
            expected_fingerprint=self.test_trusted_fp,
        )
        self.assertFalse(res.is_valid)
        self.assertTrue(len(res.error) > 0)

    def test_wrong_public_key_fails(self):
        """Signature signed by untrusted key must be rejected against trusted public key."""
        payload = "64f0b2... *VRKA-4.5.0-Build-018-Portable.zip\n"
        # Signed by untrusted key
        untrusted_sig = str(self.untrusted_key.sign(payload.encode("utf-8")))

        res = verify_openpgp_signature(
            content=payload,
            signature=untrusted_sig,
            trusted_pubkey_pem=self.test_trusted_pub_pem,
            expected_fingerprint=self.test_trusted_fp,
        )
        self.assertFalse(res.is_valid)
        self.assertIn("rejected", res.error.lower())

    def test_unknown_or_mismatched_key_fingerprint(self):
        """If expected fingerprint does not match the loaded public key, reject fail-closed."""
        payload = "Hello Manifest"
        sig = str(self.test_signer_key.sign(payload.encode("utf-8")))

        res = verify_openpgp_signature(
            content=payload,
            signature=sig,
            trusted_pubkey_pem=self.test_trusted_pub_pem,
            expected_fingerprint="0000111122223333444455556666777788889999",
        )
        self.assertFalse(res.is_valid)
        self.assertIn("fingerprint mismatch", res.error.lower())

    def test_missing_signature_rejected(self):
        """Empty or missing signature must be rejected immediately."""
        res = verify_openpgp_signature(
            content="Some payload",
            signature="",
            trusted_pubkey_pem=self.test_trusted_pub_pem,
            expected_fingerprint=self.test_trusted_fp,
        )
        self.assertFalse(res.is_valid)
        self.assertIn("missing", res.error.lower())

    def test_modified_signed_metadata_rejected(self):
        """If signed manifest is tampered after signing, verification must fail."""
        original_manifest = "abc12345... *VRKA.exe\n"
        sig = str(self.test_signer_key.sign(original_manifest.encode("utf-8")))

        tampered_manifest = "def67890... *VRKA.exe\n"
        res = verify_openpgp_signature(
            content=tampered_manifest,
            signature=sig,
            trusted_pubkey_pem=self.test_trusted_pub_pem,
            expected_fingerprint=self.test_trusted_fp,
        )
        self.assertFalse(res.is_valid)

    def test_complete_release_bundle_success(self):
        """Full bundle verification passes when signature, manifest, and artifact hash agree."""
        artifact = self.work_dir / "VRKA-4.5.0-Build-018-Portable.zip"
        artifact_content = b"Binary Payload for VRKA 4.5.0 Build 018"
        artifact.write_bytes(artifact_content)
        actual_hash = hashlib.sha256(artifact_content).hexdigest()

        manifest_text = f"{actual_hash} *VRKA-4.5.0-Build-018-Portable.zip\n"
        sig = str(self.test_signer_key.sign(manifest_text.encode("utf-8")))

        bundle_res = verify_release_artifact(
            artifact_path=artifact,
            manifest_content=manifest_text,
            signature_content=sig,
            trusted_pubkey_pem=self.test_trusted_pub_pem,
            expected_fingerprint=self.test_trusted_fp,
        )
        self.assertTrue(bundle_res.authenticated)
        self.assertTrue(bundle_res.integrity_ok)
        self.assertEqual(bundle_res.actual_sha256, actual_hash)
        self.assertEqual(bundle_res.error, "")

    def test_modified_artifact_fails_integrity(self):
        """If artifact content is modified, bundle verification fails closed."""
        artifact = self.work_dir / "VRKA-4.5.0-Build-018-Portable.zip"
        artifact.write_bytes(b"Original Genuine Payload")
        expected_hash = hashlib.sha256(b"Original Genuine Payload").hexdigest()

        manifest_text = f"{expected_hash} *VRKA-4.5.0-Build-018-Portable.zip\n"
        sig = str(self.test_signer_key.sign(manifest_text.encode("utf-8")))

        # Attacker tampers with local artifact
        artifact.write_bytes(b"Tampered Backdoored Payload")

        bundle_res = verify_release_artifact(
            artifact_path=artifact,
            manifest_content=manifest_text,
            signature_content=sig,
            trusted_pubkey_pem=self.test_trusted_pub_pem,
            expected_fingerprint=self.test_trusted_fp,
        )
        self.assertTrue(bundle_res.authenticated)  # Manifest signature was valid
        self.assertFalse(bundle_res.integrity_ok)  # Artifact hash check failed!
        self.assertIn("mismatch", bundle_res.error.lower())

    def test_checksum_and_signature_disagreement_rejected(self):
        """If manifest signature is valid but lists a fake hash, verification fails."""
        artifact = self.work_dir / "VRKA-4.5.0-Build-018-Portable.zip"
        artifact.write_bytes(b"Actual binary bytes")

        fake_hash = "0" * 64
        manifest_text = f"{fake_hash} *VRKA-4.5.0-Build-018-Portable.zip\n"
        sig = str(self.test_signer_key.sign(manifest_text.encode("utf-8")))

        bundle_res = verify_release_artifact(
            artifact_path=artifact,
            manifest_content=manifest_text,
            signature_content=sig,
            trusted_pubkey_pem=self.test_trusted_pub_pem,
            expected_fingerprint=self.test_trusted_fp,
        )
        self.assertFalse(bundle_res.integrity_ok)

    def test_malformed_key_fails_closed(self):
        """Malformed public key block must not crash or silently succeed."""
        res = verify_openpgp_signature(
            content="Test",
            signature="-----BEGIN PGP SIGNATURE-----\nfake\n-----END PGP SIGNATURE-----",
            trusted_pubkey_pem="INVALID NOT A KEY",
            expected_fingerprint="",
        )
        self.assertFalse(res.is_valid)
        self.assertIn("malformed", res.error.lower())

    def test_pinned_authoritative_key_has_valid_format(self):
        """The authoritative pinned public key in release_verifier must be syntactically valid."""
        trusted_key, _ = pgpy.PGPKey.from_blob(TRUSTED_VRKA_RELEASE_KEY_PEM.strip())
        fp = str(trusted_key.fingerprint).upper().replace(" ", "")
        self.assertEqual(fp, TRUSTED_VRKA_RELEASE_KEY_FINGERPRINT)


if __name__ == "__main__":
    unittest.main()
